apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Saudemo Regression Tests

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - 'feature/**'
      - 'fix/**'

  schedule:
    - cron: '0 22 * * 1-5'   # 22:00 UTC Mon–Fri

jobs:
  regression:
    steps:
      - name: Check out code
        uses: cloudbees-io/checkout@v1

      - name: Run Playwright Tests
        uses: docker://mcr.microsoft.com/playwright:v1.50.0-jammy
        run: |
          export HOME=/root
          npm ci
          npm run test:e2e || true
          npm run test:api || true
          npm run test:accessibility || true
