apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Saudemo Regression Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/**'
      - 'fix/**'
  schedule:
    - cron: '0 22 * * 1-5'

jobs:
  regression:
    steps:
      - name: Check out code
        uses: cloudbees-io/checkout@v1

      - name: Run E2E Tests
        uses: docker://mcr.microsoft.com/playwright:v1.50.0-jammy
        run: |
          export HOME=/root
          npm ci
          npm run test:e2e || true

      - name: Run API Tests
        uses: docker://mcr.microsoft.com/playwright:v1.50.0-jammy
        run: |
          export HOME=/root
          npm run test:api || true

      - name: Run Accessibility Tests
        uses: docker://mcr.microsoft.com/playwright:v1.50.0-jammy
        run: |
          export HOME=/root
          npm run test:accessibility || true
